magasin_index:
    path:     /
    defaults: { _controller: "SisamMallBundle:Magasin:index" }
    methods:  GET

magasin_show:
    path:     /{id}/show
    defaults: { _controller: "SisamMallBundle:Magasin:show" }
    methods:  GET

magasin_new:
    path:     /new
    defaults: { _controller: "SisamMallBundle:Magasin:new" }
    methods:  [GET, POST]

magasin_edit:
    path:     /{id}/edit
    defaults: { _controller: "SisamMallBundle:Magasin:edit" }
    methods:  [GET, POST]

magasin_delete:
    path:     /{id}/delete
    defaults: { _controller: "SisamMallBundle:Magasin:delete" }
    methods:  DELETE
